definitions:
  tests: &test
    name: Tests
    image: adaptavist/terraform:alpine-0.12.8-dev
    script:
      - terraform fmt -check -recursive -diff
      - (cd test && AWS_ACCESS_KEY_ID="${TF_TEST_AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${TF_TEST_AWS_SECRET_ACCESS_KEY}" go test)

  release: &release
    name: Release
    image: adaptavist/all-tools:latest
    caches:
      - node
    script:
      - npm install --save-dev
      - AWS_ACCESS_KEY_ID=$DEPLOY_AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY=$DEPLOY_AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION=us-east-1
        npx semantic-release -r ${BITBUCKET_GIT_HTTP_ORIGIN}
        # semantic release will perform S3 sync if successful

pipelines:
  default:
    - step: *test
  branches:
    master:
      - step: *test
      - step: *release