image: adaptavist/all-tools:openjdk16-latest-1.0.8

definitions:
  tests: &test
    name: Tests
    script:
      - terraform fmt -check -recursive -diff
      - (cd test/fixtures/default &&
        terraform init &&
        AWS_DEFAULT_REGION=us-east-1
        AWS_ACCESS_KEY_ID="${TF_TEST_AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY="${TF_TEST_AWS_SECRET_ACCESS_KEY}"
        terraform plan -out=plan.out &&
        terraform-compliance -f . -p plan.out &&
        terraform-compliance -f git:https://github.com/Adaptavist/terraform-compliance.git -p plan.out)
      - (cd test/fixtures/xray &&
        terraform init &&
        AWS_DEFAULT_REGION=us-east-1
        AWS_ACCESS_KEY_ID="${TF_TEST_AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY="${TF_TEST_AWS_SECRET_ACCESS_KEY}"
        terraform plan -out=plan.out &&
        terraform-compliance -f . -p plan.out &&
        terraform-compliance -f git:https://github.com/Adaptavist/terraform-compliance.git -p plan.out)

  release: &release
    name: Release

    caches:
      - node
    script:
      - npm install --save-dev
      - npx semantic-release -r ${BITBUCKET_GIT_HTTP_ORIGIN}
        # semantic release will perform S3 sync if successful

pipelines:
  default:
    - step: *test
  branches:
    master:
      - step: *test
      - step: *release
